variable "region" {}
variable "environment_name" {}
variable "project_name" {}
variable "cidr_block" {}
variable "vpc_name" {}
variable "pubcidr_block" {}
variable "pubsubnet_name" {}
variable "pricidr_block" {}
variable "prisubnet_name" {}
variable "igw_name" {}
variable "routecidr_block" {}
variable "routetable_name" {}
variable "pubsg_name" {}
variable "prisg_name" {}
variable "natsg_name" {}
variable "dbsub_name" {}
variable "publicinst_name" {}
variable "privateins_name" {}
variable "natinst_name" {}
variable "privateroutetable_name" {}
